### ISSUE TITLE
testdata/ is missing in sdist (since 0.11.0)

### ISSUE THREAD

**Issue by mgorny** [jamesturk/jellyfish#180]
It seems that sdist no longer includes files necessary for the tests to pass. With 0.11.0, I'm getting:

```
=============================================================== ERRORS ================================================================
______________________________________________ ERROR collecting tests/test_jellyfish.py _______________________________________________
tests/test_jellyfish.py:25: in _load_data
    with open("testdata/{}.csv".format(name), **open_kwargs) as f:
E   FileNotFoundError: [Errno 2] No such file or directory: 'testdata/jaro_winkler.csv'
        name       = 'jaro_winkler'
```

**Comment by jamesturk** [comment]
Thanks for pointing this out, I'll get a fix in the next patch release

On Tue, Mar 28, 2023, at 12:00 AM, Michał Górny wrote:
> 
> 
> It seems that sdist no longer includes files necessary for the tests to pass. With 0.11.0, I'm getting:
> 
> `=============================================================== ERRORS ================================================================
> ______________________________________________ ERROR collecting tests/test_jellyfish.py _______________________________________________
> tests/test_jellyfish.py:25: in _load_data
>     with open("testdata/{}.csv".format(name), **open_kwargs) as f:
> E   FileNotFoundError: [Errno 2] No such file or directory: 'testdata/jaro_winkler.csv'
>         name       = 'jaro_winkler'
`

**Comment by jamesturk** [comment]
just kicked off a build of v0.11.1 which should fix the issue

**Comment by mgorny** [comment]
Thanks. However, I think you forgot to update the version number in `Cargo.toml`.

**Comment by jamesturk** [comment]
indeed, fixed now 👍  thanks for your patience w/ the new process

**Comment by mgorny** [comment]
Yeah, 0.11.1 works for us. Thanks!
